### ISSUE TITLE
Impact of using TEMPSENSOR_CAL_VREFANALOG with macro __LL_ADC_CALC_TEMPERATURE on macro __HAL_ADC_CALC_TEMPERATURE and the output Temperature

### ISSUE THREAD

**Issue by rxa1031** [STMicroelectronics/stm32h7xx_hal_driver#14]
Hello,

Requesting your input on https://github.com/STMicroelectronics/STM32CubeH7/issues/111

Regards,
Rajeev

**Comment by ASELSTM** [comment]
Hi @rxa1031,

Thank you for this suggestion. However, I see you made a better one in [STM32CubeH7/#111](https://github.com/STMicroelectronics/STM32CubeH7/issues/111) . Please then allow me to close this one and to consider the other.

With regards,
