### ISSUE TITLE
No SPDX license identifiers

### ISSUE THREAD

**Issue by sebhub** [STMicroelectronics/stm32h7xx_hal_driver#21]
This software is intended to be used by applications using STMicroelectronics chips. It may be integrated in project-specific repositories. In order to manage open source software licenses, the software industry established the [Software Data Package Exchange](https://spdx.dev) standard which is an international open standard (ISO/IEC 5962:2021). It would be really nice if STMicroelectronics would support this and add SPDX license identifiers to the source files.

**Comment by ALABSTM** [comment]
Hi @sebhub,

Thank you for this interesting proposal. It has been forwarded to our quality teams. I will get back to you as soon as I have their feedback.

With regards,

**Comment by sebhub** [comment]
Thanks, this is related to https://github.com/STMicroelectronics/STM32CubeH7/issues/205. It would be nice if the code provided by STMicroelectronics could stay under the BSD-3-Clause license (instead of Apache License 2.0).

**Comment by ALABSTM** [comment]
Hi @sebhub,

Our quality team found the proposal interesting. It may eventually be considered for future releases.

Your request has been logged internally. I will get back to you should there be any update.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 126395

**Comment by ALABSTM** [comment]
Hi @sebhub,

I hope you are doing well. Back to you about your request. There is no plan in the near future to support SPDX identifiers, maybe in the long term. Anyway, the point is logged in our internal database.

I will get back to you should there be any progress. In the meanwhile, please allow me to close this issue. Thank you for your comprehension.

With regards,
