### ISSUE TITLE
usb dma无法正常工作

### ISSUE THREAD

**Issue by chengshuihang** [STMicroelectronics/stm32h7xx_hal_driver#28]
您好，我使用usbx，threadx，netduo完成了一个usb cdc主机的工程，芯片型号是STM32H743,IDE是STM32CubeIDE 1.9.0，在未开启usb dma时，系统工作正常，当我尝试打开usb dma后，它无法完成DHCP，后面经过调试，我发现是toggle_in或toggle_out判定错误导致的，它会产生如下图的现象：
![image](https://user-images.githubusercontent.com/45716763/180962778-826c68a2-3460-44fa-9511-046a88e77101.png)
观测到了这个情况后，我修改了驱动库，修复了这个问题，现在通信正常了，我不确定我修改的是否正确，您能帮我确认下吗？
修改如下：
HCD_HC_IN_IRQHandler函数：
![image](https://user-images.githubusercontent.com/45716763/180964098-dcce7e8f-f359-456d-81f7-3ab3e975ad06.png)
HCD_HC_OUT_IRQHandler函数：
![image](https://user-images.githubusercontent.com/45716763/180964231-bdd34f93-80cc-4106-af97-66974a15ee08.png)
同时，因为开启了DMA功能，所以我在USB_HC_StartXfer函数中关闭了USB_OTG_HCINTMSK_NYET，USB_OTG_HCINTMSK_ACKM，USB_OTG_HCINTMSK_NAKM中断，修改如下：
![image](https://user-images.githubusercontent.com/45716763/180964497-89dba1dc-521c-445d-adc0-ccab9c5f0bab.png)

**Comment by ALABSTM** [comment]
Hi @chengshuihang,

Thank you for this report. However, I have to close the thread as it is not in English. Thank you for your comprehension.

With regards,
