### ISSUE TITLE
HAL_UART_RegisterRxEventCallback fails if there is a transmit ongoing

### ISSUE THREAD

**Issue by dergentk** [STMicroelectronics/stm32h7xx_hal_driver#29]
**Description**
It is impossible to set an RxEventCallback (with `HAL_UART_RegisterRxEventCallback`) if a transmit is active on the port.

**How To Reproduce**
start a UART transmit with `HAL_UART_Transmit_IT`. 
then immediately thereafter call `HAL_UART_RegisterRxEventCallback`. That call _will_ fail.

**Analysis**
This is caused by the fact that `HAL_UART_RegisterRxEventCallback` checks the value of the `gState` field instead of the `RxState` like all other receive releated functions do. I don't see a reason for this difference. As far is I can tell the RxEventCallback is unrelated to transmit so checking `gState` appears to be a mistake.

**My Solution**
Changing `gState` in `HAL_UART_RegisterRxEventCallback` and `HAL_UART_UnregisterRxEventCallback` to `RxState` makes the problem go away, as expected. And it did not cause unwanted side effects in my testing.

**Comment by ASELSTM** [comment]
ST Internal Reference: 158193

**Comment by ASELSTM** [comment]
Hi @dergentk,

First excuse this late answer. Indeed, you are right, the check should be done on `RxState` and not on `gState`. This will be fixed and integrated in a future release. Thank you for reporting this and thank you fir your contribution.

With regards,

**Comment by TOUNSTM** [comment]
Fixed in https://github.com/STMicroelectronics/stm32h7xx_hal_driver/commit/a52bb3a5155f180d94d22ba7ebf26e9de2456b61
