### ISSUE TITLE
Undefined Macro Usage in stm32h7xx_hal_eth.h

### ISSUE THREAD

**Issue by HTRamsey** [STMicroelectronics/stm32h7xx_hal_driver#45]
The `ETH_DMA_Status_Flags` use macros like `ETH_DMACSR_REB_BIT_0` and `ETH_DMACSR_TEB_BIT_0` that aren't defined anywhere.

**Comment by TOUNSTM** [comment]
ST Internal Reference: 173837

**Comment by RJMSTM** [comment]
Fixed in [128346f](https://github.com/STMicroelectronics/STM32CubeL4/commit/128346f04a11c509406dd2498922bd82ed0bea86)
