### ISSUE TITLE
Fix LPI Event Interrupt (check please!)

### ISSUE THREAD

**Issue by carlo-dev-git** [STMicroelectronics/stm32h7xx_hal_driver#46]
Please check commit [https://github.com/STMicroelectronics/stm32h7xx_hal_driver/commit/5d3face3144f4b9ed70685bcbff9444962f1767c](url)

it reverted the fix merged in [https://github.com/STMicroelectronics/stm32h7xx_hal_driver/commit/404a70d4c19c124636c78801ff7c0dbc87bc4256](url)

_Originally posted by @carlo-dev-git in https://github.com/STMicroelectronics/stm32h7xx_hal_driver/issues/44#issuecomment-1953256280_

**Comment by ALABSTM** [comment]
Fixed in commit a13c7d54ce2a8493b3c2a4ae591953afee1ce5c2
