### ISSUE TITLE
Please provide a stm32h7xx_ll_dts.h/c

### ISSUE THREAD

**Issue by aurel32** [STMicroelectronics/stm32h7xx_hal_driver#56]
While there is already a HAL for the DTS sensor, it would be nice to also provide a LL interface like for other peripherals.

**Comment by ASEHSTM** [comment]
Hello @aurel32,

Thank you for your proposal. Unfortunately, there is no plan to add LL drivers for this IP at the moment. Please allow me to close this issue. Thank you for your understanding.

With Regards
