### ISSUE TITLE
stm32h7b0 and at070tn94

### ISSUE THREAD

**Issue by amirrezabv** [STMicroelectronics/stm32h7xx_hal_driver#64]
**Caution**
The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus) 

**Describe the set-up**
 * The board (either ST RPN reference or your custom board)
 * IDE or at least the compiler and its version

**Additional context**
If you have a first analysis or a patch proposal, thank you to share your proposal.

**Screenshots**

**Comment by ALABSTM** [comment]
Hi @amirrezabv,

Would you mind providing details to clarify your request please?

Thanks,

**Comment by ALABSTM** [comment]
Hi @amirrezabv,

Please allow me to close this issue as no useful information shared to allow any analysis.

With regards,
