### ISSUE TITLE
STM32H755 HRTIM_HandleTypeDef misspelling

### ISSUE THREAD

**Issue by Snolandia** [STMicroelectronics/stm32h7xx_hal_driver#66]
stm32h7xx_hal_hrtim.h 

HRTIM_InitTypeDef 

line 63

HRTIMInterruptResquests instead of HRTIMInterruptRequests

resquests -> requests

![image](https://github.com/user-attachments/assets/1d8f24d0-3424-465d-87b5-01db6ed67200)

**Comment by ALABSTM** [comment]
Hi @Snolandia,

Thank you for having drawn our attention on this. I will notify our development teams.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 188105

**Comment by KRASTM** [comment]
Fixed in commit https://github.com/STMicroelectronics/stm32h7xx_hal_driver/commit/1c33fc3126e7a5f71184167a4a1b0bc64ad787f2
