### ISSUE TITLE
TEMPSENSOR_CAL2_TEMP does not match H723 datasheet

### ISSUE THREAD

**Issue by KarstenHohmeier** [STMicroelectronics/stm32h7xx_hal_driver#67]
**Setup**
Any project using a H723 type chip.

**Describe the bug**
Value in TEMPSENSOR_CAL2_TEMP does not match the H723 datasheet.

https://github.com/STMicroelectronics/stm32h7xx_hal_driver/blame/ceda3ceeca2ee77a76d2de2ee6b560ad87c90a48/Inc/stm32h7xx_ll_adc.h#L389-L396

![image](https://github.com/user-attachments/assets/7adad965-26e2-4428-9a59-7ac7285b5476)

It seems this was updated/corrected in the datasheet in 2021 but the change did not make it into the HAL.

![image](https://github.com/user-attachments/assets/b0b5518a-44fc-4146-ac11-6132d21245ab)

**Comment by RJMSTM** [comment]
ST Internal Reference: 189983
